#!/bin/bash

USERID=$(id -u)
if [ $USERID -ne 0 ]; then
echo "Please login using Root user"
fi

VALIDATE()
{
if [ $1 -ne 0 ]; then
echo "$2 is Failed"
exit 1
else
echo "$2 is completed"
fi
}

dnf insatll nginx -y
VALIDATE $1 "Nginx Installation"

dnf insatll mysql -y
VALIDATE $1 "Nginx Installation"



