#!/bin/bash

USERID=$(id -u)
if [ $USERID -ne 0 ]
echo "Please login using Root user"
fi

VALIDATE()
{
if [ $1 -ne 0 ]
echo "$2 is Failed"
exit 1
else
echo "$2 is completed"
fi
}

dnf install nginx
VALIDATE $1 "Nginx Installation"